on:
  push:
    branches:
      - develop
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]
  workflow_dispatch:

name: ci

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - run: npm ci
      - run: npm run test:cov
      - name: 'Coverage processing'
        uses: steffendietz/clover-to-shieldsio-json-action@v1.0
        with:
          path-to-clover: 'coverage/clover.xml'
          path-to-json: 'coverage/shieldsio-coverage.json'
          style: 'flat-square'
      - name: Create or Update Gist
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GITHUB_TOKEN: ${{ secrets.HARMONIES_GITHUB_TOKEN }}
        run: |
          JSON_CONTENT=$(jq -Rs '.' < coverage/shieldsio-coverage.json)

          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "{\"files\": {\"coverage.json\": {\"content\": $JSON_CONTENT}}}" \
            https://api.github.com/gists/$GIST_ID
